version: "2"
services:

  db:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=lad"
      - "MYSQL_USER=lad"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
  spa:
    image: node:8.1
    depends_on:
      - db
    working_dir: /code
    volumes:
      - ./ladclient:/code
    entrypoint: bash /code/spa-entrypoint.sh
  
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    depends_on: 
      - spa
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
    entrypoint: bash /var/www/app-entrypoint.sh

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    depends_on:
      - app
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

volumes:
  dbdata:

